# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim"        = "2.27.1"
neorg               = { version = "8.4.0", opt = true }
"onenord.nvim"      = { version = "0.7.0", opt = true }
"lsp-zero.nvim"     = { version = "scm", opt = true }
"mason.nvim"        = { version = "1.10.0", opt = true } 
melange-nvim        = { version = "scm", opt = true }
"oil.nvim"          = { version = "2.8.0", opt = true }
tree-sitter-lua     = { version = "scm", opt = true }
nvim-lspconfig      = { version = "0.1.7", opt = true }
nvim-cmp            = { version = "0.0.1", opt = true }
cmp-nvim-lsp        = { version = "scm", opt = true }
luasnip             = { version = "2.3.0", opt = true }
tree-sitter-org     = { version = "scm", opt = true }
nvim-web-devicons   = { version = "0.99", opt = true }

[config]
plugins_dir = "plugins/"
auto_setup = false

#
# TODO: This doesn't work
#
# [plugins.oil.config]
# default_file_explorer = true
